name: Workflow 1

on:
  push:
    branches: main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Processing something
        run: |
          sleep 10
          echo "I am done!"
