name: Workflow 2

on:
  push:
    branches: main

concurrency:
  group: our-group
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Processing something
        run: |
          sleep 60
          echo "I am done!"