name: Workflow 3

on:
  push:
    branches: main

jobs:
  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: our-group
      cancel-in-progress: true

    steps:
      - name: Processing something
        run: |
          sleep 60
          echo "I am done!"

  job2:
    runs-on: ubuntu-latest
    concurrency:
      group: our-group
      cancel-in-progress: true

    steps:
      - name: Processing something
        run: |
          sleep 60
          echo "I am done!"