name: Workflow 4

on:
  push:
    branches: main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Where am i
        run: pwd
      - name: Hello
        uses: ./hello
      - name: Done
        run: echo "I am done!"
