name: Workflow 4

on:
  push:
    branches: main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        uses: grujicf/new-random@main
      - name: Done
        run: echo "I am done!"
