name: Workflow 5

on:
  push:
    branches: feat

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Where am i
        run: pwd
      - name: List files
        run: ls
      - name: Make directory
        uses: ./make-dir
      - name: List files
        run: ls
      - name: Done
        run: echo "I am done!"
