name: Workflow 5

on:
  push:
    branches: feat

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call workflow
        uses: ./github/workflows/callable.yaml
      - name: Done
        run: echo "I am done!"