name: Workflow 6

on:
  push:
    branches: main

jobs:
  job1:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/callable.yaml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Done
        run: echo "I am done!"