name: Workflow 6

on:
  push:
    branches: main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call workflow
        uses: ./github/workflows/callable.yaml
      - name: Done
        run: echo "I am done!"