name: Workflow 6

on:
  push:
    branches: main

jobs:
  job1:
    uses: ./random-workflow.yaml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Done
        run: echo "I am done!"