name: Workflow 6

on:
  push:
    branches: main

env:
  USERNAME: meowwww

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Username 1 
        run: echo $USERNAME
      - name: Print Username 2
        run: echo ${{vars.USERNAME}}