name: Workflow 6

on:
  push:
    branches: main

jobs:
  job1:
    runs-on: ubuntu-lates
    steps:
      - name: Print Username 1 
        run: echo $USERNAME
      - name: Print Username 2
        run: echo ${{vars.USERNAME}}